name: Issue Bot
description: Handle issues
author: Manuel Trezza
branding:
  icon: alert-circle
  color: green
runs:
  using: node12
  main: dist/index.js
inputs:
  issue-pattern:
    description: Regular expression which the issue body must match.
  issue-message:
    description: Message content to comment if the issue fails to match the pattern.
  github-token:
    description: GitHub token

